POST http://localhost:8080/jsongreet?businessKey=1
Content-Type: application/json

{
  "workflowdata": {
   "name" : "John",
   "language": "Spanish"
  }
}

### Get Details - Not working
http://localhost:8080/jsongreet?id=d03ecaa7-5286-4c88-92cf-f3623fd6fdfc

### OpenAPi
http://localhost:8080/q/openapi

### Swagger UI
http://localhost:8080/q/swagger-ui